#!/bin/bash
set -e

echo "=== Railway Build Environment Check ==="
echo "NODE_ENV: ${NODE_ENV:-not set}"
echo "REACT_APP_API_URL: ${REACT_APP_API_URL:-not set}"
echo "REACT_APP_STRIPE_PUBLISHABLE_KEY: ${REACT_APP_STRIPE_PUBLISHABLE_KEY:+SET}"
echo "REACT_APP_FIREBASE_API_KEY: ${REACT_APP_FIREBASE_API_KEY:+SET}"
echo "REACT_APP_FIREBASE_AUTH_DOMAIN: ${REACT_APP_FIREBASE_AUTH_DOMAIN:-not set}"
echo "REACT_APP_FIREBASE_PROJECT_ID: ${REACT_APP_FIREBASE_PROJECT_ID:-not set}"
echo "======================================="

# Export environment variables explicitly
export NODE_ENV=${NODE_ENV:-production}
export REACT_APP_API_URL=${REACT_APP_API_URL}
export REACT_APP_STRIPE_PUBLISHABLE_KEY=${REACT_APP_STRIPE_PUBLISHABLE_KEY}
export REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
export REACT_APP_FIREBASE_AUTH_DOMAIN=${REACT_APP_FIREBASE_AUTH_DOMAIN}
export REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}
export REACT_APP_FIREBASE_STORAGE_BUCKET=${REACT_APP_FIREBASE_STORAGE_BUCKET}
export REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
export REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}

# Run the webpack build
npm run webpack-build