#!/bin/bash
set -e

echo "=== Railway Runtime Environment Setup ==="
echo "PORT: ${PORT:-3000}"

# Create the env.js file with actual environment variables
cat > build/env.js << EOF
window.ENV = {
  REACT_APP_API_URL: '${REACT_APP_API_URL}',
  REACT_APP_STRIPE_PUBLISHABLE_KEY: '${REACT_APP_STRIPE_PUBLISHABLE_KEY}',
  REACT_APP_FIREBASE_API_KEY: '${REACT_APP_FIREBASE_API_KEY}',
  REACT_APP_FIREBASE_AUTH_DOMAIN: '${REACT_APP_FIREBASE_AUTH_DOMAIN}',
  REACT_APP_FIREBASE_PROJECT_ID: '${REACT_APP_FIREBASE_PROJECT_ID}',
  REACT_APP_FIREBASE_STORAGE_BUCKET: '${REACT_APP_FIREBASE_STORAGE_BUCKET}',
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: '${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}',
  REACT_APP_FIREBASE_APP_ID: '${REACT_APP_FIREBASE_APP_ID}'
};
console.log("Runtime env loaded:", window.ENV);
EOF

echo "Environment variables injected into env.js"
echo "REACT_APP_API_URL: ${REACT_APP_API_URL:-not set}"
echo "REACT_APP_STRIPE_PUBLISHABLE_KEY: ${REACT_APP_STRIPE_PUBLISHABLE_KEY:+SET}"
echo "REACT_APP_FIREBASE_API_KEY: ${REACT_APP_FIREBASE_API_KEY:+SET}"
echo "REACT_APP_FIREBASE_AUTH_DOMAIN: ${REACT_APP_FIREBASE_AUTH_DOMAIN:-not set}"
echo "REACT_APP_FIREBASE_PROJECT_ID: ${REACT_APP_FIREBASE_PROJECT_ID:-not set}"

# Start the application with dynamic port
echo "Starting server on 0.0.0.0:${PORT:-3000}"
exec serve -s build -l ${PORT:-3000} -H 0.0.0.0 --no-clipboard