# Force Docker usage for Railway deployment
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables
[variables]
PORT = "3000"
NODE_ENV = "production"